# -*- coding: utf-8 -*-

# 디버그 여부
DEBUG = False

# 포트번호
PORT = 8801

SQLALCHEMY_ECHO = DEBUG
SQLALCHEMY_POOL_RECYCLE = 7200
SQLALCHEMY_POOL_SIZE = 10
SQLALCHEMY_TRACK_MODIFICATIONS = True

MYSQL_HOST = ''
MYSQL_PORT = 3306
MYSQL_USER = ''
MYSQL_PASSWORD = ''
MYSQL_DATABASE = ''

REDIS_HOST = ''
REDIS_PORT = 6379
REDIS_PASSWORD = ''
REDIS_DEFAULT_DB_NUMBER = 2

ELASTIC_SEARCH_HOST = ''
ELASTIC_SEARCH_PORT = 9200
ELASTIC_SEARCH_INDEX = ''

NAVER_CLIENT_ID = ''
NAVER_CLIENT_SECRET = ''

GOOGLE_CLIENT_ID = ''
GOOGLE_CLIENT_SECRET = ''

LINE_CHANNEL_ACCESS_TOKEN = ''
LINE_CHANNEL_SECRET = ''

MS_COGNITIVE_SERVICE_APP_ID = ''
MS_COGNITIVE_SERVICE_APP_KEY = ''

RSA_PUBLIC_KEY_BASE64 = ''
RSA_PRIVATE_KEY_BASE64 = ''
