"""empty message

Revision ID: 706023aa6a3d
Revises: None
Create Date: 2017-02-21 14:02:18.904848
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic.
revision = '706023aa6a3d'
down_revision = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_calendar',
    sa.Column('user_uid', sa.Integer(), nullable=True),
    sa.Column('calendar_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.id'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], )
    )
    op.alter_column('calendar_platform_sync', 'user_uid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendar_platform_sync', 'user_uid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_table('user_calendar')
    # ### end Alembic commands ###