"""empty message

Revision ID: c783729e332d
Revises: d33027efecd3
Create Date: 2017-02-21 04:45:55.586681
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
# revision identifiers, used by Alembic.
revision = 'c783729e332d'
down_revision = 'd33027efecd3'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('calendar_ibfk_1', 'calendar', type_='foreignkey')
    op.drop_column('calendar', 'user_uid')
    op.add_column('calendar_platform_sync', sa.Column('user_uid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calendar_platform_sync', 'user', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calendar_platform_sync', type_='foreignkey')
    op.drop_column('calendar_platform_sync', 'user_uid')
    op.add_column('calendar', sa.Column('user_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('calendar_ibfk_1', 'calendar', 'user', ['user_uid'], ['uid'])
    # ### end Alembic commands ###