"""empty message

Revision ID: d33027efecd3
Revises: 
Create Date: 2017-02-07 15:34:10.448379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33027efecd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('user', sa.Column('invitation_code_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('signup_step_status', sa.SmallInteger(), nullable=True))
    op.create_foreign_key(None, 'user', 'invitation_code', ['invitation_code_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'signup_step_status')
    op.drop_column('user', 'invitation_code_id')
    op.drop_table('invitation_code')
    # ### end Alembic commands ###
